#!/bin/sh /etc/rc.common

USE_PROCD=1

START=50

NAME=sqlite_web
PROG="/usr/bin/sqlite_web /etc/freeradius3/sqlite_rad.db -H 192.168.1.1 -p 8000"

start_service()
{
        procd_open_instance
        procd_set_param command $PROG
        procd_close_instance
}
